-- MySQL Script generated by MySQL Workbench
-- Wed Jan  1 21:57:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mobile
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mobile` ;

-- -----------------------------------------------------
-- Schema mobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobile` DEFAULT CHARACTER SET utf8 ;
USE `mobile` ;

-- -----------------------------------------------------
-- Table `mobile`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile`.`user` ;

CREATE TABLE IF NOT EXISTS `mobile`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NULL,
  `user_number` VARCHAR(255) NULL COMMENT '	',
  `user_password` VARCHAR(45) NULL,
  `user_role` VARCHAR(45) NULL,
  `user_permission` VARCHAR(45) NULL,
  `user_sex` VARCHAR(45) NULL,
  `user_addrs` VARCHAR(45) NULL,
  `user_status` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile`.`package` ;

CREATE TABLE IF NOT EXISTS `mobile`.`package` (
  `package_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `package_monthRent` VARCHAR(45) NULL COMMENT '月租',
  `package_minCharge` VARCHAR(45) NULL,
  `package_msgCharge` VARCHAR(45) NULL,
  `package_totalTraffic` VARCHAR(45) NULL,
  PRIMARY KEY (`package_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile`.`rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile`.`rent` ;

CREATE TABLE IF NOT EXISTS `mobile`.`rent` (
  `rent_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rent_content` VARCHAR(45) NULL,
  `rent_money` VARCHAR(45) NULL,
  PRIMARY KEY (`rent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobile`.`number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile`.`number` ;

CREATE TABLE IF NOT EXISTS `mobile`.`number` (
  `number_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number_number` VARCHAR(45) NULL,
  `number_status` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `package_id_list` VARCHAR(2000) NULL,
  PRIMARY KEY (`number_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
